# Setup
title:               JD Tangney
tagline:             'Bringing Lean and UX to Security and Privacy, and vice versa'

# This descriton will appear in your document head meta (for Google search results)
# and in your feed.xml site description.
description:         >-
   UX, Lean, compliance, policy, privacy, security. 
url:                 https://jdtangney.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              John Tangney
  url:               https://about.me/jdtangney
  email:             blog@jdtangney.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             2.0.0
google_analytics_id: #UA-XXXX-Y
