# Setup
title:               JD Tangney
tagline:             'Bringing Lean to Security and Privacy, and vice versa'

# This descriton will appear in your document head meta (for Google search results)
# and in your feed.xml site description.
description:         >-
   UX, compliance, policy, privacy, security all belong inside the TDD loop. If it's not secure
   (or private or compliant) then it should not compile.
url:                 https://jdtangney.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              John Tangney
  url:               https://twitter.com/jdtangney
  email:             johnt@jdtangney.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             2.0.0
google_analytics_id: #UA-XXXX-Y
